
// executed when script is loaded
createMenu();



/*****************************
 * top-level menu for plugin *
 *****************************/

global proc createMenu()
{
	////////////////////////////////////////////////////
	// top level menu item
	////////////////////////////////////////////////////

	menu -label "Many Tiny Bubbles"
		 -parent MayaWindow
		 many_tiny_bubbles_menu;


	////////////////////////////////////////////////////
	// Create 3D Container
	////////////////////////////////////////////////////

	menuItem -label "Create 3D Container"
			 -command "create3dContainer( false, true )";
	menuItem -optionBox true
			 -command "showCreate3dContainerOptionsWindow()";
	

	////////////////////////////////////////////////////
	// Create 3D Container with Emitter
	////////////////////////////////////////////////////

	menuItem -label "Create 3D Container with Emitter"
			 -command "create3dContainerWithEmitter( false, true )";
	menuItem -optionBox true
			 -command "showCreate3dContainerWithEmitterOptionsWindow()";
	

	////////////////////////////////////////////////////
	// Add Bubble Emitter
	////////////////////////////////////////////////////

	menuItem -label "Add Bubble Emitter"
			 -command "temp()";
	menuItem -optionBox true
			 -command "temp()";
	

	////////////////////////////////////////////////////
	// Convert Mesh to Bubble Emitter
	////////////////////////////////////////////////////

	menuItem -label "Convert Mesh to Bubble Emitter"
			 -command "AddEmitterMeshCmd()";

	
	////////////////////////////////////////////////////
	// Render Simulation
	////////////////////////////////////////////////////

	menuItem -label "Render Simulation"
			 -command "showRenderWindow()";

	mtbLog( "created menu" );
}



/*****************************
 * printing in script editor *
 *****************************/

global proc mtbLog( string $print )
{
	print( "MTB: " + $print + "\n" );
}



/*****************
 * filler method *
 *****************/

global proc temp()
{
	// print action in script editor
	nlPrint( "not yet implemented\n" );
}